apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-storage
  namespace: mongodb
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: gp2
