apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: polybot
          image: omerk160/polybot:1.0.102
          ports:
            - containerPort: 31804  # App listens on 30219
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: TELEGRAM_TOKEN
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: S3_BUCKET_NAME
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: SQS_QUEUE_URL
            - name: TELEGRAM_APP_URL
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: TELEGRAM_APP_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: MONGO_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: MONGO_COLLECTION
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: MONGO_DB
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: MONGO_URI
            - name: POLYBOT_URL
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: POLYBOT_URL