apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polybot-ingress
  namespace: default
  labels:
    app.kubernetes.io/instance: polybot-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: omer-polybot-lb.devops-int-college.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: polybot-service
                port:
                  number: 31804  # Aligned with service and deployment
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: polybot-service
                port:
                  number: 31804  # Aligned with service and deployment
  tls:
    - hosts:
        - omer-polybot-lb.devops-int-college.com
      secretName: polybot-tls