apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polybot-ingress
  namespace: default
  labels:
    app.kubernetes.io/instance: polybot-app
  annotations:
    # Optional NGINX-specific annotations (customize as needed)
    nginx.ingress.kubernetes.io/rewrite-target: /  # Rewrites the URL if needed
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Enforces HTTPS
spec:
  ingressClassName: nginx  # Matches the NGINX Ingress Controller
  rules:
    - host: omer-polybot-lb.devops-int-college.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: polybot-service
                port:
                  number: 30619  # Matches your new port
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: polybot-service
                port:
                  number: 30619
  tls:
    - hosts:
        - omer-polybot-lb.devops-int-college.com
      secretName: polybot-tls  # Ensure this secret exists