apiVersion: v1
kind: Service
metadata:
  name: polybot-service
  namespace: default
  labels:
    app.kubernetes.io/instance: polybot-app
spec:
  ports:
    - name: https-port
      port: 31804  # Service port exposed to Ingress
      protocol: TCP
      targetPort: 31804  # Matches containerPort in deployment
      nodePort: 31805  # For NodePort type, must be in range 30000-32767
  selector:
    app: polybot
  type: NodePort