apiVersion: v1
kind: Service
metadata:
  name: polybot-service
  namespace: default
  labels:
    app.kubernetes.io/instance: polybot-app
spec:
  ports:
    - name: http-port  # Changed to http-port since Flask uses HTTP
      port: 31804  # Service port exposed to Ingress
      protocol: TCP
      targetPort: 31804  # Matches containerPort in deployment
      nodePort: 31804  # Matches ALB target group port
  selector:
    app: polybot
  type: NodePort