# ClusterSecretStore to authenticate with AWS Secrets Manager
# Kubernetes does not natively know how to retrieve secrets from AWS Secrets Manager
# ClusterSecretStore (provided by External Secrets Operator) acts as a bridge between AWS Secrets Manager and Kubernetes Secrets
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1  # Change to your AWS region
      auth:
          awsRole: arn:aws:iam::352708296901:role/ofekh-polybot-CP