apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-deployment
  namespace: default
  labels:
    app: yolo5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      containers:
        - name: yolo5
          image: omerk160/yolo5:1.0.60
          env:
            - name: S3_BUCKET_NAME
              value: omer-polybot-bucket
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: omer-polybot-secrets
                  key: SQS_QUEUE_URL