apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-deployment
  namespace: default
  labels:
    app: yolo5

tolerations:
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      containers:
        - name: yolo5
          image: omerk160/yolo5:1.0.62
          env:
            - name: S3_BUCKET_NAME
              value: omer-polybot-bucket
            - name: SQS_QUEUE_URL
              value: https://sqs.eu-north-1.amazonaws.com/352708296901/omer-polybot-queue